# Generated by Django 3.2.8 on 2021-10-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'verbose_name': 'ثبت اطلاعات روزانه مالی', 'verbose_name_plural': 'ثبت اطلاعات روزانه مالی'},
        ),
        migrations.AddField(
            model_name='cost',
            name='cost_revenue',
            field=models.IntegerField(null=True, verbose_name='درآمد'),
        ),
        migrations.AddField(
            model_name='cost',
            name='creditor',
            field=models.IntegerField(null=True, verbose_name='بستانکار'),
        ),
        migrations.AddField(
            model_name='cost',
            name='debtor',
            field=models.IntegerField(null=True, verbose_name='بدهکار'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_amount',
            field=models.IntegerField(null=True, verbose_name='مبلغ هزینه'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_date',
            field=models.DateField(null=True, verbose_name='تاریخ '),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_description',
            field=models.TextField(max_length=300, null=True, verbose_name='توضیحات هزینه'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_title',
            field=models.CharField(max_length=30, null=True, verbose_name='شرح هزینه'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_type',
            field=models.CharField(max_length=100, null=True, verbose_name='نوع هزینه'),
        ),
    ]
