# Generated by Django 3.2.8 on 2021-10-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20211027_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_of_description', models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات درامد')),
                ('income_date', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ ')),
                ('income_amount', models.IntegerField(blank=True, null=True, verbose_name='مبلغ درامد')),
            ],
        ),
        migrations.RemoveField(
            model_name='cost',
            name='cost_revenue',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='creditor',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='debtor',
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ هزینه'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ '),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات هزینه'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شرح هزینه'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع هزینه'),
        ),
    ]
