# Generated by Django 3.2.8 on 2021-10-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20211027_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_received', models.IntegerField(blank=True, null=True, verbose_name='دریافتی')),
                ('debtor_to_borrow', models.IntegerField(blank=True, null=True, verbose_name='قرض گرفتن')),
            ],
            options={
                'verbose_name': 'بدهکار',
                'verbose_name_plural': 'بدهکار',
            },
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'درآمد', 'verbose_name_plural': 'درآمد'},
        ),
    ]
