# Generated by Django 3.2.8 on 2021-10-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_creditor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'verbose_name': ' مالی', 'verbose_name_plural': ' مالی'},
        ),
    ]
