# Generated by Django 3.2.8 on 2021-11-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_cost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'verbose_name': 'مدیریت هزینه ها', 'verbose_name_plural': '  مدیریت هزینه ها'},
        ),
        migrations.AlterModelOptions(
            name='creditor',
            options={'verbose_name': 'بستانکار', 'verbose_name_plural': ' بستانکار'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'مدیریت درآمدها', 'verbose_name_plural': '   مدیریت درآمدها'},
        ),
    ]
