# Generated by Django 3.2.8 on 2021-10-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_cost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='creditor_description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات '),
        ),
        migrations.AddField(
            model_name='debtor',
            name='debtor_description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات '),
        ),
    ]
