# Generated by Django 3.2.8 on 2021-10-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20211031_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='creditor_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ '),
        ),
        migrations.AddField(
            model_name='debtor',
            name='debtor_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ '),
        ),
    ]
