# Generated by Django 3.2.8 on 2021-11-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20211122_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='cost_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ '),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ '),
        ),
    ]
