# Generated by Django 3.2.8 on 2021-10-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20211031_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditor',
            name='creditor_date',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='debtor_date',
        ),
        migrations.AddField(
            model_name='creditor',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ '),
        ),
        migrations.AddField(
            model_name='debtor',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ '),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ '),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ '),
        ),
    ]
