# Generated by Django 3.2.8 on 2021-11-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20211122_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='income_of_description',
        ),
        migrations.AddField(
            model_name='income',
            name='income_description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات هزینه'),
        ),
        migrations.AddField(
            model_name='income',
            name='income_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شرح هزینه'),
        ),
        migrations.AddField(
            model_name='income',
            name='income_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع هزینه'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ هزینه'),
        ),
    ]
