# Generated by Django 3.2.8 on 2021-11-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20211122_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='creditor_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شرح '),
        ),
        migrations.AddField(
            model_name='debtor',
            name='debtor_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شرح '),
        ),
    ]
