# Generated by Django 3.2.8 on 2021-10-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20211031_0618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'verbose_name': '  هزینه', 'verbose_name_plural': '  هزینه'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': ' درآمد', 'verbose_name_plural': ' درآمد'},
        ),
        migrations.RemoveField(
            model_name='income',
            name='income_amount',
        ),
        migrations.AddField(
            model_name='income',
            name='income_of_small_description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='شرح درآمد'),
        ),
        migrations.AddField(
            model_name='income',
            name='income_price',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='قیمت واحد'),
        ),
        migrations.AddField(
            model_name='income',
            name='income_the_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='مقدار درآمد'),
        ),
        migrations.AddField(
            model_name='income',
            name='income_total',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='جمع کل'),
        ),
        migrations.AddField(
            model_name='income',
            name='income_type',
            field=models.FloatField(blank=True, null=True, verbose_name='نوع درآمد'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_of_description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات'),
        ),
    ]
