# Generated by Django 3.2.8 on 2021-10-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20211031_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellChicken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'فروش مرغ',
                'verbose_name_plural': 'فروش مرغ',
            },
        ),
    ]
