# Generated by Django 3.2.8 on 2021-11-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_sellchicken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
