# Generated by Django 3.2.8 on 2021-10-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100, verbose_name='نام فارم')),
                ('number_of_halls', models.IntegerField(blank=True, default='0', null=True, verbose_name='تعداد سالن')),
                ('farm_capacity', models.TextField(blank=True, default='0', null=True, verbose_name='ظرفیت فارم ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'اطلاعات فارم',
                'verbose_name_plural': 'اطلاعات فارم',
            },
        ),
        migrations.AlterField(
            model_name='ownerinformation',
            name='number_of_farms',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد فارم'),
        ),
    ]
