# Generated by Django 3.2.8 on 2021-10-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_information', '0002_auto_20211027_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminformation',
            name='farm_capacity',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='ظرفیت فارم '),
        ),
    ]
