# Generated by Django 3.2.8 on 2021-10-31 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_information', '0005_standardinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardinformation',
            options={'verbose_name': 'اطلاعات استاندارد', 'verbose_name_plural': 'اطلاعات استاندارد'},
        ),
    ]
