# Generated by Django 3.2.8 on 2021-10-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_information', '0006_alter_standardinformation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farminformation',
            options={'verbose_name': '  اطلاعات فارم', 'verbose_name_plural': '  اطلاعات فارم'},
        ),
        migrations.AlterModelOptions(
            name='hallinformation',
            options={'verbose_name': ' اطلاعات سالن', 'verbose_name_plural': ' اطلاعات سالن'},
        ),
        migrations.AlterModelOptions(
            name='ownerinformation',
            options={'verbose_name': '   اطلاعات مالک', 'verbose_name_plural': '   اطلاعات مالک'},
        ),
    ]
