# Generated by Django 3.2.8 on 2021-11-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_information', '0006_auto_20211122_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'برنامه خاموشی',
                'verbose_name_plural': 'برنامه خاموشی',
            },
        ),
        migrations.CreateModel(
            name='ChickenInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'اطلاعات جوجه ',
                'verbose_name_plural': 'اطلاعات جوجه',
            },
        ),
        migrations.CreateModel(
            name='CourseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'اطلاعات دوره ',
                'verbose_name_plural': 'اطلاعات دوره',
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'برنامه جیره غذایی',
                'verbose_name_plural': 'برنامه جیره غذایی',
            },
        ),
        migrations.CreateModel(
            name='ShutdownProgramInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'اطلاعات خاموشی',
                'verbose_name_plural': 'اطلاعات خاموشی',
            },
        ),
        migrations.CreateModel(
            name='VaccineProgramInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'اطلاعات واکسن ',
                'verbose_name_plural': 'اطلاعات واکسن',
            },
        ),
    ]
