# Generated by Django 3.2.8 on 2021-11-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cortex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'کارتکس',
                'verbose_name_plural': 'کارتکس',
            },
        ),
        migrations.CreateModel(
            name='DrugInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'اطلاعات دارو ',
                'verbose_name_plural': 'اطلاعات دارو ',
            },
        ),
        migrations.CreateModel(
            name='GeneralCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'وضعیت کلی',
                'verbose_name_plural': 'وضعیت کلی',
            },
        ),
        migrations.CreateModel(
            name='RecordDailyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ثبت اطلاعات روزانه',
                'verbose_name_plural': 'ثبت اطلاعات روزانه',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'واکسن',
                'verbose_name_plural': 'واکسن',
            },
        ),
        migrations.CreateModel(
            name='Weightlifting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'وزن کشی',
                'verbose_name_plural': 'وزن کشی',
            },
        ),
    ]
